### ISSUE TITLE
Printer.cfg Values

### ISSUE THREAD

**Issue by arshish1612** [danorder/All-In-One-V400-SR-Official-Klipper-#1]
Are these the correct values we should start with? Copied from your current printer.cfg file. Thq SQV is very different from what Klipper recomments as 5. Also Pressure advance is 0.

max_accel: 3185
max_accel_to_decel: 1875
max_z_accel: 1500
square_corner_velocity: 333

**Comment by danorder** [comment]
Yes because a delta and should be able to take corners ideally without
limiting. Otherwise values can be set with slicer jerk depending on the
required situations. Pressure advance by default should always be 0 since
this is a material/brand specific setting. leaving a random p.a value
especially if not needed at all would most likely lead to scraping ,
overhang problems , and first layer adhesion issues.   Further the  klipper
manual is only a generic starting point for all settings to deal with the
plethora of machines which also applies to the "reference" configs on
github.  Lastly the good enough reference point  klipper leaves  up to user
to do the specifics. eg voron / ratrig are quite a bit more elaborate, not
much is left generic. . . . .

**Comment by arshish1612** [comment]
Few Questions: 

1. Wont square_corner_velocity: 333 cause excessive smoothing?
2. Also - Should we change the ACCEL 7 Acceo_to_Decl values basis what the input shaper provides?
3. Currently cannot complete the input_shaper routine. getting this error: mcu 'mcu' shutdown: adc out of range
